experiment:
  name: "insurance_premium_prediction"
  tracking_uri: ""
  artifact_location: "./metadata/mlflow/mlartifacts"
model_registry:
  model_name: "insurance_premium_prediction_model"


INGEST_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#ingest-step
  using: "csv"
  location: "./data/insurance.csv"
  loader_method: load_file_as_dataframe

INGEST_SCORING_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#batch-scoring
  using: "csv"
  location: "./data/insurance.csv"
  loader_method: load_file_as_dataframe


